/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ConexionDB;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @hp
 */
public class MDISistemaCliente extends javax.swing.JFrame {
    //FRMLogin FormularioLogin;
    FRMUsuarioJ formulariouu;
    UsuarioRegistrados formularioMostrar;
    FRMActualizarDatos formulariodatos;
    FRMCliente FormularioCliente;
    FRMProducto FormularioProducto;
    FRMProveedor FormularioProveedor;
    FRMEmpleado FormularioEmpleado;
    FRMCompra FormularioCompra;
    FRMUsuario FormularioUsuario;
    FRMAuditoria FormularioAuditoria;
    FRMPedido FormularioPedido;
    FRMBodega FormularioBodega;
    FRMTipoProducto FormularioTipo;
  
 

    public MDISistemaCliente() {
        ConexionDB.getInstance();
        initComponents();
        //FormularioLogin = new FRMLogin();
        formulariouu = new FRMUsuarioJ();
        formularioMostrar = new UsuarioRegistrados();
        formulariodatos = new FRMActualizarDatos();
        FormularioCliente = new FRMCliente();
        FormularioProducto = new FRMProducto();
        FormularioProveedor = new FRMProveedor();
        FormularioEmpleado = new FRMEmpleado();
        FormularioCompra = new FRMCompra();
        FormularioUsuario = new FRMUsuario();
        FormularioAuditoria = new FRMAuditoria();
        FormularioPedido = new FRMPedido();
        FormularioBodega = new FRMBodega();
        FormularioTipo = new FRMTipoProducto();
       
        

        //escritorio.add(FormularioLogin);
        escritorio.add(formulariouu);
        escritorio.add(formulariodatos);
        escritorio.add(FormularioCliente);
        escritorio.add(FormularioProducto);
        escritorio.add(FormularioProveedor);
        escritorio.add(FormularioEmpleado);
        escritorio.add(FormularioCompra);
        escritorio.add(FormularioUsuario);
        escritorio.add(FormularioAuditoria);
        escritorio.add(FormularioPedido);
        escritorio.add(FormularioBodega);
        escritorio.add(FormularioTipo);
        escritorio.add(formularioMostrar);
     
        
        //Aquí lo haces visible primero que todos
        //FormularioLogin.setVisible(true);
       
        
    }


       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        MNUAdministrar = new javax.swing.JMenuBar();
        itemBodega = new javax.swing.JMenu();
        ItemLogin = new javax.swing.JMenuItem();
        itemAuditoria = new javax.swing.JCheckBoxMenuItem();
        itemmBodega = new javax.swing.JCheckBoxMenuItem();
        itemCliente = new javax.swing.JCheckBoxMenuItem();
        itemCompra = new javax.swing.JCheckBoxMenuItem();
        itemEmpleado = new javax.swing.JCheckBoxMenuItem();
        itemPedido = new javax.swing.JCheckBoxMenuItem();
        itemProveedor = new javax.swing.JCheckBoxMenuItem();
        itemTipoProducto = new javax.swing.JCheckBoxMenuItem();
        itemUsuario = new javax.swing.JCheckBoxMenuItem();
        itemProducto = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        ItemDatos = new javax.swing.JMenuItem();
        ItemVer = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(51, 204, 0));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        escritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escritorioMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ropa2.jpg"))); // NOI18N
        jSplitPane1.setLeftComponent(jLabel1);

        jLayeredPane1.setLayer(jSplitPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        escritorio.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        MNUAdministrar.setInheritsPopupMenu(true);

        itemBodega.setMnemonic('f');
        itemBodega.setText("    Administrar   ");

        ItemLogin.setText("Login");
        ItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemLoginActionPerformed(evt);
            }
        });
        itemBodega.add(ItemLogin);

        itemAuditoria.setSelected(true);
        itemAuditoria.setText("Auditoria");
        itemAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAuditoriaActionPerformed(evt);
            }
        });
        itemBodega.add(itemAuditoria);

        itemmBodega.setSelected(true);
        itemmBodega.setText("Bodega");
        itemmBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmBodegaActionPerformed(evt);
            }
        });
        itemBodega.add(itemmBodega);

        itemCliente.setSelected(true);
        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        itemBodega.add(itemCliente);

        itemCompra.setSelected(true);
        itemCompra.setText("Compra");
        itemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraActionPerformed(evt);
            }
        });
        itemBodega.add(itemCompra);

        itemEmpleado.setSelected(true);
        itemEmpleado.setText("Empleado");
        itemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoActionPerformed(evt);
            }
        });
        itemBodega.add(itemEmpleado);

        itemPedido.setSelected(true);
        itemPedido.setText("Pedido");
        itemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPedidoActionPerformed(evt);
            }
        });
        itemBodega.add(itemPedido);

        itemProveedor.setSelected(true);
        itemProveedor.setText("Proveedor");
        itemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedorActionPerformed(evt);
            }
        });
        itemBodega.add(itemProveedor);

        itemTipoProducto.setSelected(true);
        itemTipoProducto.setText("Tipo Producto");
        itemTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTipoProductoActionPerformed(evt);
            }
        });
        itemBodega.add(itemTipoProducto);

        itemUsuario.setSelected(true);
        itemUsuario.setText("Registro");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        itemBodega.add(itemUsuario);

        itemProducto.setSelected(true);
        itemProducto.setText("Producto");
        itemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductoActionPerformed(evt);
            }
        });
        itemBodega.add(itemProducto);

        jMenuItem1.setText("Formulario De Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemBodega.add(jMenuItem1);

        ItemDatos.setText("Actualizar Datos");
        ItemDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemDatosActionPerformed(evt);
            }
        });
        itemBodega.add(ItemDatos);

        ItemVer.setText("Ver Usuarios");
        ItemVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemVerActionPerformed(evt);
            }
        });
        itemBodega.add(ItemVer);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        itemBodega.add(itemSalir);

        MNUAdministrar.add(itemBodega);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contactenos");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Salir");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        MNUAdministrar.add(helpMenu);

        setJMenuBar(MNUAdministrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_escritorioMouseClicked

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
       ConexionDB.desconectar();
        try {
            formularioMostrar.setClosed(true);
            FormularioCliente.setClosed(true);
            FormularioProducto.setClosed(true);
            FormularioProveedor.setClosed(true);
            FormularioEmpleado.setClosed(true);
            FormularioCompra.setClosed(true);
            FormularioUsuario.setClosed(true);
            FormularioAuditoria.setClosed(true);
            FormularioPedido.setClosed(true);
            FormularioBodega.setClosed(true);
            FormularioTipo.setClosed(true);
            formulariodatos.setClosed(true);
           
            //FormularioLogin.setVisible(false);
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(null, "No es posible salir" + ex.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        ConexionDB.desconectar();
        try {
            formularioMostrar.setClosed(true);
            FormularioCliente.setClosed(true);
            FormularioProducto.setClosed(true);
            FormularioProveedor.setClosed(true);
            FormularioEmpleado.setClosed(true);
            FormularioCompra.setClosed(true);
            FormularioUsuario.setClosed(true);
            FormularioAuditoria.setClosed(true);
            FormularioPedido.setClosed(true);
            FormularioBodega.setClosed(true);
            FormularioTipo.setClosed(true);
            formulariodatos.setClosed(true);
          
            //FormularioLogin.setVisible(false);
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(null, "No es posible salir" + ex.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void ItemVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemVerActionPerformed

        formularioMostrar.setVisible(true);
        formularioMostrar.setLocation(150, 50);
    }//GEN-LAST:event_ItemVerActionPerformed

    private void ItemDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemDatosActionPerformed
        formulariodatos.setVisible(true);
        formulariodatos.setLocation(150, 50);
        JOptionPane.showMessageDialog(null, "Busca por tu numero de cédula");
    }//GEN-LAST:event_ItemDatosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        formulariouu.setVisible(true);
        formulariouu.setLocation(150, 50);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductoActionPerformed
        FormularioProducto.setVisible(true);
        FormularioProducto.setLocation(20, 50);
    }//GEN-LAST:event_itemProductoActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        //FormularioLogin.setVisible(true);
        FormularioUsuario.setLocation(300, 10);
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTipoProductoActionPerformed
        FormularioTipo.setVisible(true);
        FormularioTipo.setLocation(150, 50);
    }//GEN-LAST:event_itemTipoProductoActionPerformed

    private void itemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedorActionPerformed
        FormularioProveedor.setVisible(true);
        FormularioProveedor.setLocation(150, 50);
    }//GEN-LAST:event_itemProveedorActionPerformed

    private void itemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPedidoActionPerformed
        FormularioPedido.setVisible(true);
        FormularioPedido.setLocation(40, 30);
    }//GEN-LAST:event_itemPedidoActionPerformed

    private void itemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoActionPerformed
        FormularioEmpleado.setVisible(true);
        FormularioEmpleado.setLocation(150, 50);
    }//GEN-LAST:event_itemEmpleadoActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        FormularioCliente.setVisible(true);
        FormularioCliente.setLocation(150, 50);
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemmBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmBodegaActionPerformed
        FormularioBodega.setVisible(true);
        FormularioBodega.setLocation(150, 20);
    }//GEN-LAST:event_itemmBodegaActionPerformed

    private void itemAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAuditoriaActionPerformed
        FormularioAuditoria.setVisible(true);
        FormularioAuditoria.setLocation(150, 50);
    }//GEN-LAST:event_itemAuditoriaActionPerformed

    private void ItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemLoginActionPerformed
        // FormularioLogin.setVisible(true);
        // FormularioLogin.setLocation(150, 50);
    }//GEN-LAST:event_ItemLoginActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void itemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraActionPerformed
        FormularioCompra.setVisible(true);
        FormularioCompra.setLocation(150, 50);
    }//GEN-LAST:event_itemCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDISistemaCliente().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemDatos;
    private javax.swing.JMenuItem ItemLogin;
    private javax.swing.JMenuItem ItemVer;
    private javax.swing.JMenuBar MNUAdministrar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JCheckBoxMenuItem itemAuditoria;
    private javax.swing.JMenu itemBodega;
    private javax.swing.JCheckBoxMenuItem itemCliente;
    private javax.swing.JCheckBoxMenuItem itemCompra;
    private javax.swing.JCheckBoxMenuItem itemEmpleado;
    private javax.swing.JCheckBoxMenuItem itemPedido;
    private javax.swing.JCheckBoxMenuItem itemProducto;
    private javax.swing.JCheckBoxMenuItem itemProveedor;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JCheckBoxMenuItem itemTipoProducto;
    private javax.swing.JCheckBoxMenuItem itemUsuario;
    private javax.swing.JCheckBoxMenuItem itemmBodega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
